query loansById($loanIds: [String]!) {
  loans(where: { id_in: $loanIds }) {
    id
    loanRequestId
    policyId
    data
    borrowedAmount
    createdAt

    loanRequest {
      id
      policyId
      amount
      status
      minAmount
      approvedAmount
      filledAmount
    }
  }

  loanChunks(where: { loanId_in: $loanIds }) {
    id
    loanId
    poolId
    rate
    borrowedAmount
    lastUpdateTs
    accruedInterest
    repaidPrincipal
  }

  _meta {
    block {
      number
      timestamp
      hash
    }
  }
}
